vim.g.mapleader = " "
vim.g.maplocalleader = " "

local map = vim.keymap.set

map("n", "<Esc>", "<cmd>nohlsearch<CR>")
map("n", "<leader>W", "<cmd>wa<CR>", { desc = "Save all files" })
map("n", "<leader>q", "<cmd>q<CR>", { desc = "Close window" })
map("n", "<leader>Q", "<cmd>qa<CR>", { desc = "Close all windows" })
map("n", "<leader>dq", vim.diagnostic.setloclist, { desc = "Diagnostics: Open diagnostic quickfix list" })
map("n", "<C-h>", "<C-w><C-h>", { desc = "Cursor: Move focus to the left window" })
map("n", "<C-l>", "<C-w><C-l>", { desc = "Cursor: Move focus to the right window" })
map("n", "<C-j>", "<C-w><C-j>", { desc = "Cursor: Move focus to the lower window" })
map("n", "<C-k>", "<C-w><C-k>", { desc = "Cursor: Move focus to the upper window" })
map("n", "<leader>w<left>", ":vertical resize +20<CR>", { desc = "Windows: Resize left" })
map("n", "<leader>w<right>", ":vertical resize -20<CR>", { desc = "Windows: Resize right" })
map("n", "<leader>w<up>", ":resize +10<CR>", { desc = "Windows: Resize up" })
map("n", "<leader>w<down>", ":resize -10<CR>", { desc = "Windows: Resize down" })
map("n", "gh", "g^", { desc = "Cursor: Go to line start" })
map("n", "gl", "g$", { desc = "Cursor: Go to line end" })
map("n", "<C-u>", "<C-u>zz", { desc = "Cursor: Go up and centering" })
map("n", "<C-d>", "<C-d>zz", { desc = "Cursor: Go down and centering" })
map("v", "<", "<gv", { desc = "Move: Don't disable highlight on text move left" })
map("v", ">", ">gv", { desc = "Move: Don't disable highlight on text move right" })
map("v", "J", ":m '>+1<CR>gv=gv", { desc = "Move: Move selected line down" })
map("v", "K", ":m '<-2<CR>gv=gv", { desc = "Move: Mode selected line up" })
map("n", "n", "nzzzv", { desc = "Search: Centering next search result" })
map("n", "N", "Nzzzv", { desc = "Search: Centering previous search result" })
map("n", "<leader>wh", "<cmd>split<CR>", { desc = "Windows: Split horizontally" })
map("n", "<leader>wv", "<cmd>vsplit<CR>", { desc = "Windows: Split vertically" })
map({ "n", "v" }, "x", [["_x]], { desc = "Clipboard: Don't copy to clipboard removed text" })
map({ "n", "v" }, "d", [["_d]], { desc = "Clipboard: Don't copy to clipboard removed text" })
map({ "n", "v" }, "dd", [["_dd]], { desc = "Clipboard: Don't copy to clipboard removed line" })
map("i", "<C-l>", "<Right>", { desc = "Cursor: Move cursor right" })
map("i", "<C-h>", "<Left>", { desc = "Cursor: Move cursor left" })
