vim.opt.breakindent = true -- Перенесенная строка повторяет отступ
vim.opt.clipboard = "unnamedplus" -- Использовать буфер обмена
vim.opt.confirm = true -- Спросить, что делать с несохраненными или файлами, доступными только для чтения
vim.opt.cursorline = true -- Подсветить строку на экране, где находится курсор
vim.opt.expandtab = true -- Использовать пробелы при вставке <Tab>
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()" -- Выражение, используемое, когда 'foldmethod' установлен в "expr"
vim.opt.foldlevel = 99 -- Закрыть свертки с уровнем выше этого
vim.opt.foldlevelstart = 99 -- Уровень сверток ('foldlevel') при начале редактирования файла
vim.opt.foldmethod = "expr" -- Тип свертки
vim.opt.foldnestmax = 10 -- Максимальная глубина свертки
vim.opt.ignorecase = true -- Игнорировать регистр в поисковых шаблонах
vim.opt.linebreak = true -- Переносить длинные строки на пробелах
vim.opt.list = true -- Показывать <Tab> и <EOL> (конец строки)
vim.opt.listchars = "tab:>-,trail:." -- Символы для отображения в режиме списка
vim.opt.mouse = "a" -- Включить использование щелчков мыши
vim.opt.number = true -- Вывести номер строки перед каждой строкой
vim.opt.relativenumber = true -- Показать относительный номер строки перед каждой строкой
vim.opt.scrolloff = 8 -- Минимальное количество строк выше и ниже курсора
vim.opt.shiftwidth = 2 -- Количество пробелов для шага (авто)отступа
vim.opt.sidescrolloff = 8 -- Минимальное количество столбцов слева и справа от курсора
vim.opt.signcolumn = "yes" -- Когда и как отображать колонку знаков
vim.opt.smartcase = true -- Не игнорировать регистр, если шаблон содержит прописные буквы
vim.opt.softtabstop = 2 -- Количество пробелов, которые используется <Tab> при редактировании
vim.opt.spellfile = os.getenv("HOME") .. "/.config/nvim/spell/dictionary.utf-8.add" -- Файлы, в которых zg и zw хранят слова
vim.opt.spelllang = "ru_ru,en_us" -- Язык(и) для проверки орфографии
vim.opt.splitbelow = true -- Новое окно из сплита будет ниже текущего
vim.opt.splitright = true -- Новое окно будет расположено справа от текущего
vim.opt.swapfile = false -- Использовать ли swap-файл для буфера
vim.opt.tabstop = 2 -- Количество пробелов, которые <Tab> использует в файле
vim.opt.termguicolors = true -- Включить 24-битный RGB цвет в TUI
vim.opt.wildmode = "longest:full,full" -- Режим для расширения командной строки с помощью 'wildchar'
